#!/bin/bash -eu

function exists() {
	if ! which "${1}" > /dev/null ; then
		echo "Missing ${1}"
		exit 1
	fi
}

function canlink() {
	l=`ldconfig -v 2>/dev/null | grep ${1}`
	if [[ -z "${l}" ]] ; then
		echo "Can't link to ${1}"
		exit 1
	fi
}

# Some basic utilities weren't installed.
ls
touch a
mv a b
cp b a
rm a b
sleep 1
df -h `pwd`

# Make sure the languages are all included.
exists go
exists java
exists node
exists python
exists python3
# exists ruby

# Make sure these commands work as well.
exists netstat
exists grep

# Make sure we have mono.
exists mono

# Make sure we can import subprocess in a spawned python job.
# This also verifies the Python version.
python istest.py
python3 istest.py

# Make sure that libuv.so (for node) and libpcre.so (for ruby) are linkable.
# canlink libuv.so # Might not need this.
canlink libpcre.so

# Verify we are at Ruby 2.2 or greater.
# rubyver=`ruby --version | awk '{print $2}'`
# let major=`echo ${rubyver} | cut -d. -f1`
# let minor=`echo ${rubyver} | cut -d. -f2`

# if [[ ${major} -lt 2 ]] ; then
# 	echo "Incompatible Ruby major version."
# 	exit 1
# elif [[ ${major} -eq 2 ]] && [[ ${minor} -lt 2 ]] ; then
# 	echo "Incompatible Ruby minor version."
# 	exit 1
# fi

# Make sure we can create a temporary file in /tmp.
if ! touch /tmp/sanity.tmp ; then
    echo "Could not create temporay file."
    exit 1
elif ! rm /tmp/sanity.tmp ; then
    echo "Could not delete temporary file."
fi
