apiVersion: v1
kind: Namespace
metadata:
  name: joshua
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: joshua-sa
  namespace: joshua
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: joshua-job-role
  namespace: joshua
rules:
- apiGroups:
  - ""
  - extensions
  - batch
  resources:
  - jobs
  - pods
  verbs:
  - get
  - list
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: joshua-job-role-binding
  namespace: joshua
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: joshua-job-role
subjects:
- kind: ServiceAccount
  name: joshua-sa
  namespace: joshua
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: joshua:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: joshua-sa
  namespace: joshua
