name: Joshua

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Install fdb and dependencies
        run: |
          sudo mkdir -p /var/lib/foundationdb/data
          wget https://github.com/apple/foundationdb/releases/download/6.3.18/foundationdb-clients_6.3.18-1_amd64.deb
          wget https://github.com/apple/foundationdb/releases/download/6.3.18/foundationdb-server_6.3.18-1_amd64.deb
          echo "d18ad92f081827e723fe1e554948a587a0b6069f95f050564821b3ecdb8b4daf  foundationdb-clients_6.3.18-1_amd64.deb" >> checks.txt
          echo "d5e452b71f85d6e5d16a2d707b8699a4ae1addeaaa456f002007b81d30bb39bf  foundationdb-server_6.3.18-1_amd64.deb" >> checks.txt
          sha256sum -c checks.txt && sudo dpkg -i *.deb
          sudo pip3 install -r test-requirements.txt

      - name: Test
        run: |
          pytest -v
